### ISSUE TITLE
Research and Determine RasPi Hardware Requirements

### ISSUE THREAD

**Issue by cabeese** [cabeese/crab-tracker#18]
# Background

Currently, we are working with Raspberry Pi Model Zeros for our development. While this has been sufficient thus far (some outstanding SPI issues not accounted for), we may need to upgrade to more powerful hardware to accommodate the small touch screen that we would like to add to the project. We'd like to know if the combination of the screen and the precise timing needed for SPI will require more powerful hardware.

# Requirements

* Determine what kind of resources will be needed to display something on a small SPI-connected Pi screen. (Bonus/possibly prerequisite: will we need to boot into a full GUI-based OS to work with the screen, or can we draw to it manually with SPI somehow?)
* Compare the specs of a standard RasPi and the Zero. How much faster is the processor on the larger model? What other considerations should we take into account?
* Determine if using the screen while also requiring some amount of *reliable* (though potentially slow) performance from the board is possible on the Zero or if we'll need to buy a larger version.

The various available models are viewable [here](https://www.raspberrypi.org/products/).

**Comment by mimaxwell** [comment]
Decided to use a raspberry pi touch screen and the raspberry pi 3 b that is recommended to connect with it:

-  While it's possible to use a pi zero and a touch screen, connecting a pi 3 b to the raspberry pi touch screen is a standard configuration. There's lots of guides and online support that can provide aid if we need it. 

-  The raspberry pi 3 b does not communicate with the pi screen using SPI, which will simplify using SPI to communicate with the Arduino.

- The quad core of the pi 3 b will allow the various portions of the system to run in different threads. The pi zero has only a single core.
