### ISSUE TITLE
Create Test Data for Unit Tests

### ISSUE THREAD

**Issue by cabeese** [cabeese/crab-tracker#19]
# Background

We have a great team working on the GUI design and implementation. As they begin to develop the GUI, they'll want some test data to play with.

# Requirements

The test data can be completely arbitrary, and must include the required parameters (direction (vector), ID, and status/boolean value).

Before providing data, however, we must agree on and formally define the data formatting (e.g. object types). The ID and status are easy (`int`); the format of the returned vector should also be straightforward, but we need to define coordinates and potentially other formatting concerns. For instance, we could pass a 2-dimensional array `[float, float]` or create a `struct` with `x` and `y` components and so on.

Given the GUI team's timeline, we should have this data within about two weeks, sometime around the start of February.

**Comment by enalaiya** [comment]
Not longer relevant
